// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeyoheyiquyskhfcbmdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhleW9oZXlpcXV5c2toZmNibWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTM1NzYsImV4cCI6MjA2NDYyOTU3Nn0.VXp7Imf892v1zhTCrqeIDak0rxFzsjBdRgqpsU51Jrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);